### ISSUE TITLE
all action on imdb is failing

### ISSUE THREAD

**Issue by noyse27** [RileyXX/IMDB-Trakt-Syncer#56] opened 2023-07-25 22:04 UTC
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

after starting th escript the action imdb => Trakt works but all action trakt =>imdb is failing

```
Successfully signed in to IMDB
Processing Trakt Data
Processing Trakt Data Complete
Processing IMDB Data
Processing IMDB Data Complete
Setting Trakt Watchlist Items
 - Adding item (1 of 4): Dreifacher Rittberger (1987) to Trakt Watchlist
 - Adding item (2 of 4): Madre (2016) to Trakt Watchlist
 - Adding item (3 of 4): Tatort: Angriff auf Wache 08 (2019) to Trakt Watchlist
 - Adding item (4 of 4): Check. Check (2019) to Trakt Watchlist
Setting Trakt Watchlist Items Complete
Setting IMDB Watchlist Items
 - Adding item (1 of 10): The Beasts (2022) to IMDB Watchlist
   - Failed to add item (1 of 10): The Beasts (2022) to IMDB Watchlist (tt15006566)
 - Adding item (2 of 10): TÁR (2022) to IMDB Watchlist
   - Failed to add item (2 of 10): TÁR (2022) to IMDB Watchlist (tt14444726)
 - Adding item (3 of 10): Step Brothers (2008) to IMDB Watchlist
   - Failed to add item (3 of 10): Step Brothers (2008) to IMDB Watchlist (tt0838283)
 - Adding item (4 of 10): Tulsa King (2022) to IMDB Watchlist
   - Failed to add item (4 of 10): Tulsa King (2022) to IMDB Watchlist (tt16358384)
 - Adding item (5 of 10): Derry Girls (2018) to IMDB Watchlist
   - Failed to add item (5 of 10): Derry Girls (2018) to IMDB Watchlist (tt7120662)
 - Adding item (6 of 10): Silo (2023) to IMDB Watchlist
   - Failed to add item (6 of 10): Silo (2023) to IMDB Watchlist (tt14688458)
 - Adding item (7 of 10): The Dead Girls Detective Agency (2018) to IMDB Watchlist
   - Failed to add item (7 of 10): The Dead Girls Detective Agency (2018) to IMDB Watchlist (tt9169850)
 - Adding item (8 of 10): The Wolf House (2018) to IMDB Watchlist
   - Failed to add item (8 of 10): The Wolf House (2018) to IMDB Watchlist (tt8173728)
 - Adding item (9 of 10): The Rescue (2020) to IMDB Watchlist
   - Failed to add item (9 of 10): The Rescue (2020) to IMDB Watchlist (tt9283920)
 - Adding item (10 of 10): Mandibles (2020) to IMDB Watchlist
   - Failed to add item (10 of 10): Mandibles (2020) to IMDB Watchlist (tt10375106)
Setting IMDB Watchlist Items Complete
Setting Trakt Ratings
 - Rating TV show (1 of 2): An Idiot Abroad (2010): 10/10 on Trakt
 - Rating TV show (2 of 2): Hanna (2019): 3/10 on Trakt
Setting Trakt Ratings Complete
Setting IMDB Ratings
 - Rating movie: (1 of 3380) Godzilla Raids Again (1955): 7/10 on IMDB
   - Failed to rate movie: (1 of 3380) Godzilla Raids Again (1955): 7/10 on IMDB (tt0048127)
 - Rating movie: (2 of 3380) The Ghosts of Monday (2022): 6/10 on IMDB
   - Failed to rate movie: (2 of 3380) The Ghosts of Monday (2022): 6/10 on IMDB (tt13655580)
 - Rating movie: (3 of 3380) Fall (2022): 8/10 on IMDB
   - Failed to rate movie: (3 of 3380) Fall (2022): 8/10 on IMDB (tt15325794)
 - Rating movie: (4 of 3380) Small Engine Repair (2021): 8/10 on IMDB
   - Failed to rate movie: (4 of 3380) Small Engine Repair (2021): 8/10 on IMDB (tt9789042)
```

### Environment

win 11
Python 3.11.4

**Comment by RileyXX** [comment] 2023-07-26 02:56
Hi thanks for reporting this! In order to help locate the issue and possibly implement a fix, please provide any relevant error logs and follow the troubleshooting instructions below.

There are a lot of reasons this could be happening but these are a few possibilities:
- The IMDB website pages are taking a long time to load and the script is not waiting long enough
- The IMDB website is not loading correctly
- School or public internet is blocking elements of the website
- A/B design testing where users may see different versions of the IMDB website causing the script to fail

### Provide any relevant error logs:
There should be some error logs associated with this. If you could please paste any relevant error logs here that would be helpful. If you installed with pip the error `log.txt` will most likely be located at `C:\Users\YOUR_USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\IMDBTraktSyncer`. The most recent errors will be at the bottom of the `log.txt` file.

### Troubleshooting:
Unfortunately I am unable to replicate this issue, so I will need your assistance in order to locate the issue and possibly implement a fix.

In order to verify that the IMDB pages are loading correctly, you can unhide the browser window and see exactly what the script is doing while it runs. To to this, open `IMDBTraktSyncer.py` in a text editor like Notepad++. This file should be located `C:\Users\YOUR_USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\IMDBTraktSyncer`. Look for the line `options.add_argument("--headless=new")`, put a `#` before it like this `#options.add_argument("--headless=new")` then save it. Then run the script again and it will unhide the browser so you can see exactly what's happening when the script is rating/adding items on IMDB. This might give some clues to what's happening. 

<img width="557" alt="06-19-2023_327" src="https://github.com/RileyXX/IMDB-Trakt-Syncer/assets/49823202/aa0f11cf-4e20-46d1-891d-ed0d7ad25950">

If the IMDB website appears to be loading correctly, when the script is running with the browser window unhidden try saving the webpage.html when a movie page loads by using ctrl+s. Then you can upload that html file here so I can investigate any potential issues.

To undo the changes to the changes to the `IMDBTraktSyncer.py` file simply remove the `#` you added earlier and save it.

**Comment by noyse27** [comment] 2023-07-26 19:43
i'll try ;)

**Comment by noyse27** [comment] 2023-07-26 19:58
headless see video

https://github.com/RileyXX/IMDB-Trakt-Syncer/assets/25564572/77665852-b579-41f1-a38b-eae848ceeb9b

**Comment by RileyXX** [comment] 2023-07-26 20:25
Thank you! I see what the issue is now. This looks to be a similar issue that was reported by another user here https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/46 but I wasn't able to figure out exactly what was causing it. 

Thanks to the video you provided I see the issue (at least in your case) is caused by the setting `Show reference view with full cast and crew (advanced view)` located here https://www.imdb.com/preferences/general. 

When enabled, the links to the movie page `https://www.imdb.com/title/tt10521092/` are being redirected to `https://www.imdb.com/title/tt10521092/reference` which has a different layout causing the script to fail.

I will work on implementing a fix for this in the next patch. In the meantime, as a workaround you can untick the setting here `Show reference view with full cast and crew (advanced view)` https://www.imdb.com/preferences/general. Then run the script again and it should run without issue. Let me know if this works for you!

**Comment by RileyXX** [comment] 2023-07-26 22:08
This should be fixed now in [v1.6.0](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v1.6.0). 

If you installed with pip can upgrade to the latest version using the following:
````
python -m pip install IMDBTraktSyncer --upgrade
````

Let me know if this fixes it for you!

**Comment by noyse27** [comment] 2023-07-27 05:09
thx very much seems to work now
<img width="903" alt="07_09_10" src="https://github.com/RileyXX/IMDB-Trakt-Syncer/assets/25564572/31861abe-ccef-4c95-90be-6197e1f91ccc">

**Comment by RileyXX** [comment] 2023-07-27 06:27
> thx very much seems to work now 

Very cool that's good to hear and thanks for confirming! Without the detailed information you provided this would have been very difficult to troubleshoot. Thanks for taking the time!

**Closed by RileyXX** 2023-07-27 06:27 UTC
Labels: bug
